# Generated by Django 2.2.12 on 2020-05-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a test description for a test item that costs a test price using testing products'),
            preserve_default=False,
        ),
    ]
